### ISSUE TITLE
Mac build throws an error message in Mac OS 11 - Big Sur 11.2.3

### ISSUE THREAD

**Issue by akselkreis** [jordanfb/PicoCADToolKit#4] opened 2021-03-23 19:22 UTC
Description of the problem: When opening the application in Big Sur 11.2.3, a message pops up that states: "You can’t open the application “PicoToolkit” because it may be damaged or incomplete." - The app doesn't launch.

![Screen Shot 2021-03-23 at 3 21 09 PM](https://user-images.githubusercontent.com/1050994/112205679-67cd1100-8beb-11eb-88e2-68d8f92e0f04.png)

**Comment by jordanfb** [comment] 2021-03-23 20:52
Oh no! Thanks for reporting the issue. Any chance you could try out an older release or two to see if they work? I suspect that it has to do with the GitHub actions automatic build system but I don't have a Mac to test it on. If you could try the original Mac update https://github.com/jordanfb/PicoCADToolKit/releases/tag/v0.3.1 which was actually built by someone manually on a Mac I would be really grateful. If that works then I suspect it’s the automatic build setup. If you wanted to you could try the https://github.com/jordanfb/PicoCADToolKit/releases/tag/v0.4 version to see if it works but I suspect it won’t. In the meantime I’ll poke around to see if I can figure out the issue on my end.
If this is particularly urgent for whatever reason you can always run the code yourself since it all works on OSX but that’s obviously much less useful than a nicely built application!

**Comment by jordanfb** [comment] 2021-03-23 22:31
I checked and can confirm that the first version linked (the Mac release) works, so if you want to use that version temporarily while I we figure this out that works.

**Comment by akselkreis** [comment] 2021-03-23 23:26
Perfect, I'll use that build. Thanks for the help!

**Comment by jordanfb** [comment] 2021-03-29 17:16
Alright! I think I fixed the issue with the release of v0.5, turns out what I thought was an application was just a folder that I had named .app... oops! The release also fixes a few issues with dark mode on OSX not showing the text on buttons. Once it's confirmed to work I'll close the issue.

**Comment by akselkreis** [comment] 2021-03-29 19:25
The latest build is working for me & the dark mode fixes are most welcome! Thanks again for the great tool!

**Closed as completed** 2021-03-29 20:07 UTC
